### PR TITLE
fix(experimental): Apply prioritisation fee

### LINKED ISSUE #864: CommonConfig's prioritisationFee is not used and might lead to confusion
https://github.com/CityOfZion/neon-js/blob/804b20a34872be3d6ae70bc036bdf367fc50b280/packages/neon-js/src/experimental/types.ts#L5

### PR DESCRIPTION
**Pull request by ixje**
Fix #864

### CODE REVIEW

File: packages/neon-js/src/experimental/helpers.ts [hunk 1]
```diff
@@ -224,6 +224,18 @@ export async function addFees(
     );
   }
 
+  if (config.networkFeeOverride && config.prioritisationFee) {
```
Comment (snowypowers) [inline packages/neon-js/src/experimental/helpers.ts:227]: can we do the precondition checks at the start of the method so we can do an early exit.

**Review by snowypowers — APPROVED** [review]
